name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone test cases
        uses: actions/clone@v2
        with:
          url: https://github.com/seriquynh/enjoy-coding.git

      - name: Execute tests
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        run: |
          pip3 install pyyaml \
          python3 test.py
